# Generated by Django 4.1.1 on 2022-09-16 09:42

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('baseenty_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.baseenty')),
                ('name', models.CharField(max_length=128, verbose_name='Nomi')),
                ('slug', models.SlugField(max_length=128)),
                ('description', models.TextField(verbose_name='Tavsif')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faolmi')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child', to='product.category', verbose_name='Ajdod')),
            ],
            options={
                'verbose_name': '2. Kategoriya ',
                'verbose_name_plural': '2. Kategoriyalar ',
            },
            bases=('main.baseenty', models.Model),
            managers=[
                ('_tree_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('baseenty_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.baseenty')),
                ('code', models.IntegerField(verbose_name='Kod')),
                ('title', models.CharField(max_length=128, verbose_name='Nomi')),
                ('description', models.TextField(verbose_name='Tavsif')),
                ('units', models.CharField(choices=[('dona', 'Dona'), ('kg', 'Kg')], max_length=50, verbose_name='Birlik')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faolmi')),
                ('slug', models.SlugField(max_length=128)),
                ('image', models.ImageField(default='images/product/default.png', upload_to='images/product/')),
                ('category_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='product.category', verbose_name='Kategoriya')),
            ],
            options={
                'verbose_name': '1. Maxsulot ',
                'verbose_name_plural': '1. Maxsulotlar ',
                'ordering': ['-created_at'],
            },
            bases=('main.baseenty',),
        ),
    ]
