# Generated by Django 4.1.1 on 2022-09-16 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Kategoriya ', 'verbose_name_plural': 'Kategoriyalar '},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-created_at'], 'verbose_name': 'Maxsulot ', 'verbose_name_plural': 'Maxsulotlar '},
        ),
    ]
