# Generated by Django 4.1.1 on 2022-09-19 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0002_alter_category_options_alter_product_options'),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('baseenty_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.baseenty')),
                ('name', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=20, unique=True)),
                ('address', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('stir', models.IntegerField(unique=True)),
            ],
            bases=('main.baseenty',),
        ),
        migrations.CreateModel(
            name='SupplyBill',
            fields=[
                ('baseenty_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='main.baseenty')),
                ('bill_no', models.AutoField(primary_key=True, serialize=False)),
                ('time', models.DateTimeField(auto_now=True)),
                ('sup_supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supply_supplier', to='supply.supplier')),
            ],
            bases=('main.baseenty',),
        ),
        migrations.CreateModel(
            name='SupplyItem',
            fields=[
                ('baseenty_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.baseenty')),
                ('quantity', models.IntegerField(default=1)),
                ('per_price', models.IntegerField(default=1)),
                ('total_price', models.IntegerField(default=1)),
                ('bill_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supply.supplybill')),
                ('sup_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supply_product', to='product.product')),
            ],
            options={
                'ordering': ['-id'],
            },
            bases=('main.baseenty',),
        ),
    ]
