# Generated by Django 4.1.1 on 2022-09-20 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supply', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='supplier',
            options={'verbose_name': "Ta'minotchi", 'verbose_name_plural': "Ta'minotchilar"},
        ),
        migrations.AlterModelOptions(
            name='supplybill',
            options={'ordering': ['-bill_no'], 'verbose_name': 'Kirim', 'verbose_name_plural': 'Kirimlar'},
        ),
        migrations.AlterModelOptions(
            name='supplyitem',
            options={'ordering': ['-id'], 'verbose_name': 'Kirim maxsuloti', 'verbose_name_plural': 'Kirim maxsulotlari'},
        ),
        migrations.AddField(
            model_name='supplier',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
