# Generated by Django 4.1.1 on 2022-09-20 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_category_options_alter_product_options'),
        ('supply', '0003_alter_supplyitem_total_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale', models.BooleanField(default=True)),
                ('sup_qty', models.FloatField(default=0)),
                ('sale_qty', models.BooleanField(default=True)),
                ('total_bal_qty', models.FloatField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
                ('supply', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='supply.supplyitem')),
            ],
            options={
                'verbose_name': 'Ombor ',
                'verbose_name_plural': 'Omborlar ',
            },
        ),
    ]
