# Generated by Django 4.1.1 on 2022-09-16 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='departament',
            options={'verbose_name': "1. Bo'lim ", 'verbose_name_plural': "2. Bo'limlar "},
        ),
        migrations.AlterModelOptions(
            name='role',
            options={'verbose_name': '2. Lavozim ', 'verbose_name_plural': '2. Lavozimlar '},
        ),
        migrations.AlterField(
            model_name='employee',
            name='dept',
            field=models.ManyToManyField(to='employee.departament', verbose_name="B'lim"),
        ),
    ]
