# Generated by Django 4.1.1 on 2022-09-16 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_alter_departament_options_alter_role_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='departament',
            options={'ordering': ['dep_id'], 'verbose_name': "Bo'lim ", 'verbose_name_plural': "Bo'limlar "},
        ),
        migrations.AlterModelOptions(
            name='employee',
            options={'verbose_name': 'Hodim ', 'verbose_name_plural': 'Hodimlar '},
        ),
        migrations.AlterModelOptions(
            name='role',
            options={'verbose_name': 'Lavozim ', 'verbose_name_plural': 'Lavozimlar '},
        ),
        migrations.AlterField(
            model_name='employee',
            name='dept',
            field=models.ManyToManyField(to='employee.departament', verbose_name="Bo'lim"),
        ),
        migrations.AlterField(
            model_name='employee',
            name='role',
            field=models.ManyToManyField(related_name='em_role', to='employee.role', verbose_name='Lavozim'),
        ),
    ]
